AllCops:

  TargetRubyVersion: '3.3'
Metrics/BlockLength:
  Exclude:
    - lib/proxified.rb
    - spec/**/*
    - Guardfile
    - proxified.gemspec

Naming/MethodName:
  Exclude:
    - lib/proxified.rb
